version: '3.8'

services:
  postgres:
    container_name: veera_apprisal_postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin834
      POSTGRES_DB: hr_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5477:5432"

  backend:
    container_name: veera_apprisal_backend
    build: ./Backend
    ports:
      - "3079:3079"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: admin834
      DB_NAME: hr_db

  frontend:
    container_name: veera_apprisal_frontend
    build: ./Frontend
    ports:
      - "8111:80"
    depends_on:
      - backend

  hr:
    container_name: veera_apprisal_hr
    build: ./HR
    ports:
      - "8112:80"
    depends_on:
      - backend

volumes:
  pgdata:

